version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: sh -c "sleep 5 && python manage.py makemigrations --settings=phishingidentify.docker-settings && python manage.py migrate --settings=phishingidentify.docker-settings && python manage.py runserver 0.0.0.0:8000 --settings=phishingidentify.docker-settings"
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=phiseado
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres